jobs:
  assign_reviewer:
    if: github.event.pull_request.draft == false
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: shufo/auto-assign-reviewer-by-files@v1.1.4
      with:
        config: .github/assign-by-files.yml
        token: ${{ secrets.GITHUB_TOKEN }}
name: Auto Assign Pull Request
on:
  repository_dispatch:
    types: trigger-ga___auto-assign.yml
