jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: PR-Labeler
on:
  repository_dispatch:
    types: trigger-ga___labeler.yml
